name: fcole90-hexgl-webapp
version: '1.5'
summary: Webapp for HexGL
description: |
    /!\ Warning: this game has been reported to not work properly on some devices. Please, consider it a beta. If you know any solution to improve the support, please, contact me.
    
    You can run it with the command: fcole90-hexgl-webapp.hexgl-webapp
    
    HexGL is a futuristic, fast-paced racing game built by Thibaut Despoulain using HTML5, Javascript and WebGL and a tribute to the original Wipeout and F-Zero series.
    HexGL was built with love using three.js, a 3D library built on top of WebGL and maintained by Mr.doob and AlteredQualia. 
    I'd also like to thank Nobiax for the great metalic road texture, Charnel for the HexMKI base mesh, and all the beta-testers.

grade: stable
confinement: strict

apps:
  hexgl-webapp:
    command: webapp-launcher --enable-back-forward http://hexgl.bkcore.com/play %u
    plugs:
      - browser-sandbox
      - network
      - network-bind
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  webapp-container:
    after: [desktop-ubuntu-app-platform,webapp-helper]
    plugin: nil

